name: Conty AutoRelease CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Conty
        run: |
          chmod +x create-arch-bootstrap.sh create-conty.sh
          sed -i 's/sed/#sed/g' create-arch-bootstrap.sh
          sudo ./create-arch-bootstrap.sh && ./create-conty.sh

          if [ "$(stat -c%s conty.sh)" -gt 2097152000 ]; then
            split -b 2097152000 --numeric-suffixes=1 conty.sh conty.sh_part
            rm conty.sh
          fi

      - uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
         tag_name: continuous
         github_token: ${{ secrets.GITHUB_TOKEN }}
         delete_release: true

      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "continuous"

      - uses: softprops/action-gh-release@v1
        with:
          files: ./conty.sh*
          prerelease: true
          draft: false
          tag_name: continuous
          name: Continuous build
